-- SQL Query to Insert QR Code Data for Customer: 9f6c74f6-f581-475a-aa6f-22c7df0363ad

-- First, let's check what cars this customer has:
SELECT * FROM cars WHERE customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad';

-- Check customer profile data:
SELECT id, full_name, email, phone, address, village FROM profiles 
WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad';

-- Check if customer has active monthly pass:
SELECT * FROM monthly_pass 
WHERE customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad' 
AND active = true;

-- ============================================================
-- INSERT QR CODE - Use one of these queries based on your car
-- ============================================================

-- OPTION 1: Insert QR code for a specific car with monthly pass (Manual Insert)
-- Replace the values in UPPERCASE with actual data from above queries

INSERT INTO public.qr_codes (
  id,
  car_id,
  customer_id,
  qr_code_data,
  qr_code_image,
  customer_name,
  customer_email,
  customer_mobile,
  customer_address,
  customer_village,
  monthly_pass_id,
  monthly_pass_active,
  monthly_pass_expiry,
  car_brand,
  car_model,
  car_number_plate,
  is_active,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'CAR_ID_HERE', -- Replace with actual car ID from cars table
  '9f6c74f6-f581-475a-aa6f-22c7df0363ad',
  '{"carId":"CAR_ID_HERE","customerId":"9f6c74f6-f581-475a-aa6f-22c7df0363ad","customerName":"CUSTOMER_NAME","customerEmail":"CUSTOMER_EMAIL","customerPhone":"CUSTOMER_PHONE","customerAddress":"CUSTOMER_ADDRESS","customerVillage":"CUSTOMER_VILLAGE","carBrand":"CAR_BRAND","carModel":"CAR_MODEL","numberPlate":"NUMBER_PLATE","monthlyPassActive":true,"monthlyPassExpiry":"2025-12-31T00:00:00Z","generatedAt":"2025-12-10T00:00:00Z"}',
  'QR_IMAGE_BASE64_HERE', -- This should be a base64 encoded QR image or image URL
  'CUSTOMER_FULL_NAME',
  'customer@email.com',
  'PHONE_NUMBER',
  'CUSTOMER_ADDRESS',
  'CUSTOMER_VILLAGE',
  'MONTHLY_PASS_ID_HERE', -- Replace with actual monthly pass ID if exists
  true, -- monthly_pass_active
  '2025-12-31'::timestamp, -- monthly_pass_expiry date
  'CAR_BRAND',
  'CAR_MODEL',
  'CAR_NUMBER_PLATE',
  true,
  NOW(),
  NOW()
);

-- ============================================================
-- OPTION 2: Complete Insert with Actual Data (Example)
-- ============================================================
-- Assuming customer has: Car with ID 'abc123', Name 'John Doe', Email 'john@example.com'

INSERT INTO public.qr_codes (
  id,
  car_id,
  customer_id,
  qr_code_data,
  qr_code_image,
  customer_name,
  customer_email,
  customer_mobile,
  customer_address,
  customer_village,
  monthly_pass_id,
  monthly_pass_active,
  monthly_pass_expiry,
  car_brand,
  car_model,
  car_number_plate,
  is_active,
  created_at,
  updated_at
) 
SELECT 
  gen_random_uuid() as id,
  c.id as car_id,
  '9f6c74f6-f581-475a-aa6f-22c7df0363ad' as customer_id,
  jsonb_build_object(
    'carId', c.id,
    'customerId', '9f6c74f6-f581-475a-aa6f-22c7df0363ad',
    'customerName', p.full_name,
    'customerEmail', p.email,
    'customerPhone', p.phone,
    'customerAddress', COALESCE(p.address, c.number_plate),
    'customerVillage', COALESCE(p.village, 'Not Specified'),
    'carBrand', c.brand,
    'carModel', c.model,
    'numberPlate', c.number_plate,
    'monthlyPassActive', CASE WHEN mp.id IS NOT NULL THEN true ELSE false END,
    'monthlyPassExpiry', COALESCE(mp.valid_till, NOW() + INTERVAL '30 days'),
    'generatedAt', NOW()
  )::text as qr_code_data,
  '' as qr_code_image, -- Empty for now, will be generated by API
  p.full_name as customer_name,
  p.email as customer_email,
  p.phone as customer_mobile,
  COALESCE(p.address, c.number_plate) as customer_address,
  COALESCE(p.village, 'Not Specified') as customer_village,
  mp.id as monthly_pass_id,
  CASE WHEN mp.id IS NOT NULL THEN true ELSE false END as monthly_pass_active,
  mp.valid_till as monthly_pass_expiry,
  c.brand as car_brand,
  c.model as car_model,
  c.number_plate as car_number_plate,
  true as is_active,
  NOW() as created_at,
  NOW() as updated_at
FROM cars c
LEFT JOIN profiles p ON p.id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'
LEFT JOIN monthly_pass mp ON mp.car_id = c.id AND mp.active = true
WHERE c.customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'
AND NOT EXISTS (
  SELECT 1 FROM qr_codes qr WHERE qr.car_id = c.id
);

-- ============================================================
-- OPTION 3: Insert QR codes for ALL cars of this customer
-- ============================================================

INSERT INTO public.qr_codes (
  id,
  car_id,
  customer_id,
  qr_code_data,
  qr_code_image,
  customer_name,
  customer_email,
  customer_mobile,
  customer_address,
  customer_village,
  monthly_pass_id,
  monthly_pass_active,
  monthly_pass_expiry,
  car_brand,
  car_model,
  car_number_plate,
  is_active,
  created_at,
  updated_at
) 
SELECT 
  gen_random_uuid() as id,
  c.id as car_id,
  '9f6c74f6-f581-475a-aa6f-22c7df0363ad' as customer_id,
  jsonb_build_object(
    'carId', c.id,
    'customerId', '9f6c74f6-f581-475a-aa6f-22c7df0363ad',
    'customerName', p.full_name,
    'customerEmail', p.email,
    'customerPhone', p.phone,
    'customerAddress', COALESCE(p.address, c.number_plate),
    'customerVillage', COALESCE(p.village, 'Not Specified'),
    'carBrand', c.brand,
    'carModel', c.model,
    'numberPlate', c.number_plate,
    'monthlyPassActive', CASE WHEN mp.id IS NOT NULL THEN true ELSE false END,
    'monthlyPassExpiry', COALESCE(mp.valid_till, NOW() + INTERVAL '30 days'),
    'generatedAt', NOW()
  )::text as qr_code_data,
  '' as qr_code_image,
  p.full_name as customer_name,
  p.email as customer_email,
  p.phone as customer_mobile,
  COALESCE(p.address, c.number_plate) as customer_address,
  COALESCE(p.village, 'Not Specified') as customer_village,
  mp.id as monthly_pass_id,
  CASE WHEN mp.id IS NOT NULL THEN true ELSE false END as monthly_pass_active,
  mp.valid_till as monthly_pass_expiry,
  c.brand as car_brand,
  c.model as car_model,
  c.number_plate as car_number_plate,
  true as is_active,
  NOW() as created_at,
  NOW() as updated_at
FROM cars c
LEFT JOIN profiles p ON p.id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'
LEFT JOIN monthly_pass mp ON mp.car_id = c.id AND mp.active = true
WHERE c.customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'
AND NOT EXISTS (
  SELECT 1 FROM qr_codes qr WHERE qr.car_id = c.id
);

-- ============================================================
-- OPTION 4: Update existing QR code with new data
-- ============================================================

UPDATE public.qr_codes
SET 
  qr_code_data = jsonb_build_object(
    'carId', car_id,
    'customerId', customer_id,
    'customerName', (SELECT full_name FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
    'customerEmail', (SELECT email FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
    'customerPhone', (SELECT phone FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
    'customerAddress', (SELECT COALESCE(address, 'Not Specified') FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
    'customerVillage', (SELECT COALESCE(village, 'Not Specified') FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
    'generatedAt', NOW()
  )::text,
  customer_name = (SELECT full_name FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
  customer_email = (SELECT email FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
  customer_mobile = (SELECT phone FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
  customer_address = (SELECT COALESCE(address, 'Not Specified') FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
  customer_village = (SELECT COALESCE(village, 'Not Specified') FROM profiles WHERE id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'),
  updated_at = NOW()
WHERE customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad';

-- ============================================================
-- Verify the inserted data
-- ============================================================

SELECT 
  id,
  car_id,
  customer_id,
  customer_name,
  customer_email,
  customer_mobile,
  customer_village,
  car_number_plate,
  monthly_pass_active,
  monthly_pass_expiry,
  created_at
FROM public.qr_codes
WHERE customer_id = '9f6c74f6-f581-475a-aa6f-22c7df0363ad'
ORDER BY created_at DESC;
